#!/bin/sh

set -o pipefail # exit on pipeline error
set -e # exit on error
set -u # variable must exist
# set -x # verbose

die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "1 argument required, $# provided"

DOMAIN=${1}

echo | openssl s_client -servername ${DOMAIN} -connect ${DOMAIN}:443 -showcerts | openssl x509 -text
